/** @type {import('tailwindcss').Config} */
const DARK_COLORS = {
  'inverse-primary': '#8a5100',
  primary: '#ffb86f',
  'on-secondary-container': '#c0b2ac',
  'surface-container-highest': '#3a3330',
  'surface-variant': '#3a3330',
  'tertiary-container': '#79aa88',
  'on-background': '#ece0db',
  'on-primary-container': '#512d00',
  'on-secondary-fixed-variant': '#4f4540',
  'error-container': '#93000a',
  'on-error-container': '#ffdad6',
  'on-tertiary': '#05381f',
  secondary: '#d2c4bd',
  error: '#ffb4ab',
  'primary-container': '#d98e3a',
  'inverse-on-surface': '#352f2c',
  'on-secondary-fixed': '#221a16',
  'primary-fixed-dim': '#ffb86f',
  'on-surface-variant': '#d7c3b2',
  'on-secondary': '#372f2a',
  'on-tertiary-fixed': '#00210f',
  'surface-container': '#241e1b',
  'secondary-container': '#4f4540',
  'on-tertiary-container': '#0d3e24',
  'surface-container-high': '#2f2925',
  'on-error': '#690005',
  'secondary-fixed': '#efdfd9',
  'secondary-fixed-dim': '#d2c4bd',
  surface: '#17120f',
  'tertiary-fixed-dim': '#a0d2ae',
  'on-primary-fixed': '#2c1600',
  background: '#17120f',
  'surface-bright': '#3e3834',
  'outline-variant': '#524437',
  'on-surface': '#ece0db',
  'inverse-surface': '#ece0db',
  'surface-tint': '#ffb86f',
  'tertiary-fixed': '#bbefc9',
  tertiary: '#a0d2ae',
  'surface-container-lowest': '#120d0a',
  'surface-container-low': '#201a17',
  'surface-dim': '#17120f',
  outline: '#a08d7e',
  'on-tertiary-fixed-variant': '#215034',
  'on-primary': '#4a2800',
  'on-primary-fixed-variant': '#693c00',
  'primary-fixed': '#ffdcbe',
}

/**
 * Light Material 3 palette used by the "Super Admin" (Platform Admin) console.
 * Namespaced as `pa-*` so it can coexist with the dark Studio OS palette above.
 */
const PLATFORM_COLORS = {
  error: '#ba1a1a',
  'on-secondary-fixed-variant': '#5e402f',
  'on-secondary-container': '#795845',
  'surface-dim': '#dbdad6',
  'on-tertiary-fixed': '#2f1405',
  'on-primary': '#ffffff',
  primary: '#9a4100',
  'primary-fixed': '#ffdbcb',
  'secondary-fixed': '#ffdbca',
  outline: '#8a7267',
  'primary-fixed-dim': '#ffb690',
  surface: '#fbf9f5',
  'outline-variant': '#ddc1b3',
  'tertiary-fixed': '#ffdbca',
  'on-surface': '#1b1c1a',
  'on-secondary-fixed': '#2d1608',
  'on-error-container': '#93000a',
  'on-primary-container': '#fffbff',
  'on-tertiary': '#ffffff',
  'on-secondary': '#ffffff',
  'on-surface-variant': '#574238',
  'surface-container-highest': '#e4e2de',
  tertiary: '#79533e',
  'inverse-on-surface': '#f2f0ed',
  'primary-container': '#bd5611',
  background: '#fbf9f5',
  'surface-container-high': '#eae8e4',
  'surface-container-lowest': '#ffffff',
  'on-tertiary-fixed-variant': '#623e2b',
  'inverse-primary': '#ffb690',
  'on-background': '#1b1c1a',
  'on-primary-fixed-variant': '#783100',
  'surface-container': '#efeeea',
  'on-tertiary-container': '#fffbff',
  'surface-variant': '#e4e2de',
  'surface-tint': '#9e4300',
  'tertiary-container': '#956b55',
  'inverse-surface': '#30312e',
  'secondary-container': '#fed1b9',
  secondary: '#795745',
  'secondary-fixed-dim': '#e9bda7',
  'surface-bright': '#fbf9f5',
  'on-primary-fixed': '#341100',
  'error-container': '#ffdad6',
  'surface-container-low': '#f5f3ef',
  'tertiary-fixed-dim': '#eebca2',
  'on-error': '#ffffff',
}

module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{html,ts}', '!./src/stitch_barbershop_landing_and_login/**'],
  // Preflight is disabled on purpose: the app already has its own global reset in
  // styles.scss and runs Angular Material, which a preflight reset would fight with.
  corePlugins: { preflight: false },
  theme: {
    extend: {
      colors: { ...DARK_COLORS, pa: PLATFORM_COLORS },
      borderRadius: { DEFAULT: '0.125rem', lg: '0.25rem', xl: '0.5rem', full: '0.75rem' },
      spacing: {
        'margin-lg': '3rem',
        'space-lg': '1.5rem',
        'margin-sm': '1rem',
        'gutter-lg': '2rem',
        'space-xs': '0.25rem',
        'gutter-sm': '1rem',
        gutter: '1.5rem',
        'space-xl': '2.5rem',
        space: '0.5rem',
        'space-sm': '0.5rem',
        margin: '1.5rem',
        'space-md': '1rem',
      },
      fontFamily: {
        display: ['Vollkorn', 'serif'],
        'data-tabular': ['Inter', 'sans-serif'],
        'display-mobile': ['Vollkorn', 'serif'],
        'headline-md': ['Vollkorn', 'serif'],
        'body-md': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Vollkorn', 'serif'],
        'headline-lg-mobile': ['Vollkorn', 'serif'],
        'headline-lg': ['Vollkorn', 'serif'],
        'title-md': ['Inter', 'sans-serif'],
        'label-lg': ['Inter', 'sans-serif'],
        'display-lg': ['Vollkorn', 'serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-sm': ['Vollkorn', 'serif'],
        'title-lg': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        display: ['44px', { lineHeight: '52px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'title-md': ['15px', { lineHeight: '22px', letterSpacing: '0em', fontWeight: '600' }],
        'data-tabular': ['13px', { lineHeight: '18px', letterSpacing: '-0.01em', fontWeight: '500' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '600' }],
        'display-mobile': ['32px', { lineHeight: '40px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'body-sm': ['12px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '400' }],
        'headline-sm': ['18px', { lineHeight: '26px', letterSpacing: '-0.005em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0em', fontWeight: '400' }],
        'headline-lg-mobile': ['26px', { lineHeight: '34px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
