ALTER TABLE "appointment_payments" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "appointments" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "audit_events" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "branches" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "staff_profiles" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "staff_schedules" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "staff_services" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "staff_time_off" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "cash_registers" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "cash_sessions" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "cash_transactions" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "branch_services" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "service_categories" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "services" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "customers" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "permissions" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "roles" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "user_branches" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "user_roles" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "branch_inventory" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "inventory_movements" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "goods_receipts" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "purchase_order_items" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "purchase_orders" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "suppliers" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "promotion_branches" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "promotion_redemptions" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "promotion_services" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
ALTER TABLE "promotions" ADD COLUMN "tenant_id" uuid;--> statement-breakpoint
DO $$ DECLARE target_tenant uuid; BEGIN SELECT id INTO target_tenant FROM platform_tenants WHERE slug = 'navaja-demo' LIMIT 1; IF target_tenant IS NULL THEN RAISE EXCEPTION 'Tenant navaja-demo must exist before migration'; END IF;
UPDATE appointment_payments SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE appointments SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE audit_events SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE branches SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE staff_profiles SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE staff_schedules SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE staff_services SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE staff_time_off SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE cash_registers SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE cash_sessions SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE cash_transactions SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE branch_services SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE service_categories SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE services SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE customers SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE permissions SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE role_permissions SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE roles SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE sessions SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE user_branches SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE user_roles SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE users SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE branch_inventory SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE inventory_movements SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE products SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE goods_receipts SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE purchase_order_items SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE purchase_orders SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE suppliers SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE promotion_branches SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE promotion_redemptions SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE promotion_services SET tenant_id = target_tenant WHERE tenant_id IS NULL; UPDATE promotions SET tenant_id = target_tenant WHERE tenant_id IS NULL;
END $$;--> statement-breakpoint
ALTER TABLE "appointment_payments" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "appointments" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "audit_events" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "branches" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "staff_profiles" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "staff_schedules" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "staff_services" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "staff_time_off" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "cash_registers" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "cash_sessions" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "cash_transactions" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "branch_services" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "service_categories" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "services" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "customers" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "permissions" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "role_permissions" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "roles" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "sessions" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "user_branches" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "user_roles" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "users" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "branch_inventory" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "inventory_movements" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "products" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "goods_receipts" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "purchase_order_items" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "purchase_orders" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "suppliers" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "promotion_branches" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "promotion_redemptions" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "promotion_services" ALTER COLUMN "tenant_id" SET NOT NULL; ALTER TABLE "promotions" ALTER COLUMN "tenant_id" SET NOT NULL;--> statement-breakpoint